name: Update Data

on:
  workflow_dispatch:
  schedule:
    # Every hour
    - cron: "0 * * * *"
  push:
    paths:
      - ".github/workflows/data.yml" # run evertime gh action config file is changed
      - "src/**" # run everytime config files is changed (change on author/images/series or any logic in scraping)
      - "assets/**" # run everytime assets is changed (change on manually added assets)

permissions:
  contents: write

jobs:
  data:
    name: Check the repos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: |
          git config --global user.name "Update Data"
          git config --global user.email "alfonsusac@gmail.com"
      - run: bun src/index.ts