name: Update Data

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/types.yml" # run evertime gh action config file is changed
      - "src/update-types.ts" # run everytime config files is changed (change on author/images/series or any logic in scraping)
      - "src/types/index.ts" # run everytime types is changed

permissions:
  contents: write

jobs:
  data:
    name: Update types and bump version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: |
          git config --global user.name "Update Data"
          git config --global user.email "alfonsusac@gmail.com"
      - run: bun i
      - run: bun src/update-types.ts